variables:
  DOTNET_SDK_VERSION: '3.1.201'
  DOTNET_PACKAGE_TYPE: 'sdk'
  RUBY_VERSION: '2.5'

jobs:
- template: build/tmpl/jobs.yml
  parameters:
    name: macOS
    vmImage: 'macOS 10.15'
    installRuby: 'false'

- template: build/tmpl/jobs.yml
  parameters:
    name: Linux
    vmImage: 'Ubuntu 18.04'

- template: build/tmpl/jobs.yml
  parameters:
    name: Windows
    vmImage: 'windows-2019'

